# Generated by Django 5.0.6 on 2024-05-21 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='category2',
            new_name='category',
        ),
    ]
