# Generated by Django 5.0.6 on 2024-05-21 13:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('text', models.TextField(verbose_name='Содержание')),
                ('category2', models.CharField(choices=[('sport', 'спорт'), ('scince', 'наука'), ('cooking', 'кулинария'), ('technic', 'технологии')], max_length=50, verbose_name='Категория')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('my_image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300, verbose_name='Комментарий')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('data', models.DateTimeField(verbose_name='Дата')),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.FloatField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)], verbose_name='Оценка')),
                ('comment', models.TextField(verbose_name='Комментарий')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
            ],
        ),
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Ваша проблема')),
                ('nomer', models.IntegerField(verbose_name='Ваш номер(без плюса)')),
                ('data', models.DateTimeField(verbose_name='Дата')),
            ],
        ),
    ]
